name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies with Yarn
        run: yarn install

      - name: Run the tests
        run: npm run test

      - name: Run the app
        run: npm start
